zazuko/kopflos

- index.js
- lib/SparqlView.js
- test/SparqlView.js
Some endpoints don't support update queries on the query URL. With this PR the update queries are detected by simple text search and the update URL is used.
> Hack for SPARQL update queries

- index.js
Adding SPARQL client to the `req` object so that any handler can perform queries
```js
async (req, res, next) => {
const dataset = rdf.dataset()
const const result = await req.sparql.constructQuery('CONSTRUCT ...')
dataset.import(await result.quadStream())
res.graph(dataset)
}
```
> feat: expose sparql client to express handlers

- middleware.js
- package.json
Update @rdfjs/express-handler to use the baseIRI feature
> feat: forward base IRI option to @rdfjs/express-handler

- Api.js
- lib/middleware/resource.js
- lib/middleware/waitFor.js
- middleware.js
- package.json
- test/Api.test.js
- test/support/api.ttl
This PR makes the `.fromFile` method of `Api` chainable by doing the actual file reading and parsing in `.init`. Also the `.rebase` is done in init in the order of the method calls.
> use chaining api in Api class

- StoreResourceLoader.js
- examples/blog/server.js
- lib/middleware/resource.js
- middleware.js
- test/StoreResourceLoader.test.js
- test/support/store/__index.nt
This PR moves the code to load the resource for class/property operations to a separate class `StoreResourceLoader` and allows using custom loaders not based on the RDF/JS Store interface.
> moved resource loading code to StoreResourceLoader class

- README.md
- lib/middleware/operation.js
By adding the selected operation to `req.hydra` the handler middleware will have access to metadata about the operation.
Specifically, I'd like to use it to get the `sh:Shape` object of `hydra:expects`.
> feat: attach selected operation to express request object

- examples/blog/api.ttl
- examples/blog/blog.js
- lib/middleware/iriTemplate.js
- test/iriTemplate.test.js
- test/resource.test.js
This PR makes it possible to handle IRI Template requests with multiple values of a mapped variable, handing both flavours `foo=bar,baz` and `foo=bar&foo=baz`
> fix(iri-template): support multiple query params values

- lib/middleware/iriTemplate.js
- test/iriTemplate.test.js
- test/support/iriTemplateMappingBuilder.js
This adds support for parsing IRI template queries where `hydra:ExplcitRepresentation` is required.
The test cases are taken from the [examples shown in the specification](http://www.hydra-cg.com/spec/latest/core/#example-22-the-different-variable-representations)
> feat: support hydra:ExplicitRepresentation for iri templates

- lib/log.js
- lib/middleware/iriTemplate.js
- lib/middleware/operation.js
- lib/middleware/resource.js
- middleware.js
- test/operation.test.js
- test/support/operationTestCases.ttl
I implemented a bunch of improvements to the operation selection process:
2. Only consider class' operations when the resource URI equals request URI
3. For property operations, only select those where property object equals request URI
1. Fail request when multiple operations are found
4. Fail request when loader registry fails to load operation
This fixe a bunch of broken scenarios such as multiple properties supporting a given method (like multiple nested collections which accept `POST`) and calling a random property operation when the class does not support a given method
> Refactor operation middleware

- lib/middleware/waitFor.js
- middleware.js
- package.json
Wrapping all middleware which returns a promise in `middleware-async` ensures that promise rejection is handled gracefully.
Currently the API just logs an unhandled rejection and not response is ever sent to the client.
> fix: handle promise rejection in handlers

- lib/middleware/waitFor.js
- middleware.js
- test/middleware.test.js
- test/resource.test.js
I'd like to have access to the `IncomingMessage` inside the resource loader. This way the loaded resource can be modified before passing it to the operation middleware.
This way I can dynamically alter the routing, for example by adding of removing `rdf:type` from resource based on auth information.
> feat: add middleware hook between resource loader and operation

- StoreResourceLoader.js
- examples/blog/blog.js
- examples/blog/category.js
- examples/blog/post.js
- lib/middleware/operation.js
- test/StoreResourceLoader.test.js
- test/operation.test.js
Proposed change to allow loaders to only load a minimum quads necessary for finding operations (working name `prefechDataset`) with the full resource dataset available on-demand using an async function.
We could also add a similar `.quadStream()` function?
> fix: introduce separate dataset only for finding operations

- lib/middleware/operation.js
- test/operation.test.js
Since `0.6` introduce a breaking change making it difficult to get a pointer out of a resource object, this PR adds a handy function which wraps the request using clownface
**Before** 
```js
import clownface from 'clownface'
function handler(req) {
const pointer = clownface(req.hydra.resource)
}
```
**Now**
Turned async because the entire dataset representation is no longer fetched in full by the loader
```js
async function handler(req) {
const pointer = await req.hydra.resource.clownface()
}
```
> feat: utility getter of clownface resource pointer

- lib/middleware/apiHeader.js
- middleware.js
- test/apiHeader.test.js
- test/middleware.test.js
This PR aims to improve a possible issue encountered when hosting a hydra-box inside a sub-path router where the API URL can be incorrect
> fix: initializing API Documentation in router

- lib/middleware/operation.js
Currently, when no operation is found, a `NotFoundError` is returned.
This way no handlers are called after hydra-box. It's not necessary in order to return a 404 and unnecessary limiting
> fix: allow handlers after hydra-box

- lib/middleware/resource.js
I would like to be able to access the express request object from resource loader.
This will allow me to access various request-context objects such as a preconfigured RDF code loader or logger
> feat: access Request object from resource loader

- mocha-setup.js
- package-lock.json
- packages/core/graphs/shorthands.ttl
- packages/core/index.ts
- packages/core/lib/Kopflos.ts
- packages/core/lib/env/KopflosNamespaceFactory.ts
- packages/core/lib/resourceLoader.ts
- packages/core/package.json
- packages/core/test/lib/Kopflos.test.ts
- packages/core/test/lib/Kopflos.test.ts.trig
- packages/core/test/lib/__snapshots__/resourceLoader.test.ts.snap
- packages/core/test/lib/handler.test.ts
- packages/core/test/lib/loadApi.test.ts
- packages/core/test/lib/resourceLoader.test.ts
- packages/core/test/lib/resourceLoader.test.ts.trig
- packages/core/test/lib/resourceShape.test.ts
- packages/core/test/support/in-memory-clients.ts
- packages/core/test/support/ns.ts
- packages/mocha-chai-rdf/matchers.ts
- packages/mocha-chai-rdf/package.json
- packages/mocha-chai-rdf/store.ts
This inserts nodes `kopflos:DescribeLoader` and `kopflos:OwnGraphLoader` so that end users will not have to repeat them when setting up API and Resource Shape
```
[ a code:EcmaScriptModule ;
code:link <node:@kopflos-cms/core/resourceLoaders.js#describe> ] .
```
> feat: insert shorthand code implementations to API graph

- .changeset/popular-lizards-cough.md
- package-lock.json
- packages/core/lib/Kopflos.ts
- packages/core/test/lib/Kopflos.test.ts
- packages/express/BodyWrapper.ts
- packages/express/package.json
- packages/express/test/BodyWrapper.test.ts
- packages/express/test/handlers/body-handler.ts
- packages/express/test/index.test.ts
Since express has no easy way to determine if a body is present in a request, I changed the behavior to always create the `body` in handler args and let the implementors worry about checking if RDF is present in the message.
For other kids of payloads, I change `body.raw` so that it can be used with `co-body` to parse in user code when necessary. This avoids baking in express `body-parser` but we may still revisit what we do here when it comes to multi-part bodies
> refactor: bodies

- .changeset/hungry-rats-notice.md
- package-lock.json
- packages/core/lib/Kopflos.ts
- packages/core/lib/env/SparqlClientFactory.ts
- packages/core/package.json
- packages/core/test/lib/env/SparqlClientFactory.test.ts
Further simplifies programmatic set up of SPARQL clients, only requiring one instance. The other will be created with same settings.
> feat: simplify endpoint intitialization

- package-lock.json
- packages/core/lib/Kopflos.ts
- packages/core/lib/resourceLoader.ts
- packages/core/package.json
- packages/core/plugin/shorthandTerms.ts
- packages/core/plugins.ts
- packages/core/test/lib/Kopflos.test.ts
- packages/core/test/lib/loadApi.test.ts
- packages/core/test/plugins.test.ts
- packages/core/test/support/plugin.ts
- packages/express/index.ts
- packages/plugin-deploy-resources/index.ts
- packages/plugin-deploy-resources/package.json
- packages/plugin-deploy-resources/test/index.test.ts
Since we now have the plugin functionality, I thought I would move the code which inserts the shorthand terms `kl:DescribeLoader` to a plugin. That made me realise too that the logic of loading plugins is unnecessarily tied to the `Kopflos` class. Instead, I moved that out and now we can initialise the instance with pre-loaded plugin. Good for testing :)
> refactor: make a plugin for shorthand terms

- .changeset/eleven-carrots-battle.md
- .changeset/friendly-pandas-fry.md
- .changeset/wise-tomatoes-breathe.md
- .github/workflows/tests.yml
- example/kopflos.config.ts
- package-lock.json
- packages/cli/index.ts
- packages/cli/lib/command/build.ts
- packages/cli/lib/command/deploy.ts
- packages/cli/lib/command/serve.ts
- packages/cli/lib/config.ts
- packages/cli/package.json
- packages/cli/test/fixtures/config.with-watch.json
- packages/cli/test/kopflos.config.ts
- packages/cli/test/lib/command/serve.test.ts
- packages/cli/test/lib/config.test.ts
- packages/core/lib/Kopflos.ts
- packages/core/plugin/shorthandTerms.ts
- packages/core/test/lib/Kopflos.test.ts
- packages/core/test/lib/loadApi.test.ts
- packages/express/index.ts
- packages/plugin-deploy-resources/index.ts
- packages/plugin-deploy-resources/package.json
- packages/plugin-deploy-resources/test/__snapshots__/index.test.ts.snap
- packages/plugin-deploy-resources/test/index.test.ts
- packages/plugin-deploy-resources/test/resources/bar.ttl
This adds watch mode. 
* Enabled by default in `kopflos serve --mode development`. 
* Can be switched off with `kopflos serve --mode development --no-watch`
* Can be forced enabled in production mode `kopflos serve --watch`
Always watches for changes in the config file. Additional paths to watch are defined in the config
```js
export default {
watch: ['lib', 'handlers']
}
```
Not need to watch vite root directory since vite development server has its own hot module reload.
Resources deployed using plugin `@kopflos-cms/plugin-deploy-resources` are watched independently and do not trigger a full server restart. This behavior can be changed by adding them to the main watch list and disabling the plugin's watch
```js
export default {
watch: ['lib', 'handlers', 'resources'],
plugins: { …
```
> feat: watch mode
